from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FORBIDDEN_NAMES = {".DS_Store", "__pycache__", ".git", ".release"}
FORBIDDEN_SUFFIXES = {".pyc", ".pyo"}
SECRET_PATTERNS = [
    re.compile(r"-----BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY-----"),
    re.compile(r"\bsk-[A-Za-z0-9_-]{20,}"),
    re.compile(r"(?i)(api[_-]?key|secret|token)\s*[:=]\s*['\"][^'\"]{16,}['\"]"),
]


def ignore(_: str, names: list[str]) -> set[str]:
    ignored: set[str] = set()
    for name in names:
        if name in FORBIDDEN_NAMES or name.startswith("._") or Path(name).suffix in FORBIDDEN_SUFFIXES:
            ignored.add(name)
    return ignored


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def assert_clean(target: Path) -> None:
    for path in target.rglob("*"):
        if path.name in FORBIDDEN_NAMES or path.name.startswith("._") or path.suffix in FORBIDDEN_SUFFIXES:
            raise SystemExit(f"forbidden generated metadata: {path.relative_to(target)}")
        if path.is_file() and path.suffix in {".md", ".py", ".json", ".yml", ".yaml", ".sh", ".mdc"}:
            text = path.read_text(encoding="utf-8", errors="ignore")
            if any(pattern.search(text) for pattern in SECRET_PATTERNS):
                raise SystemExit(f"possible secret in {path.relative_to(target)}")


def run(args: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, cwd=cwd, text=True, capture_output=True, check=False)


def sanitize_demo_output(output: str) -> str:
    sanitized = output
    for temp_root in {tempfile.gettempdir(), str(Path(tempfile.gettempdir()).resolve())}:
        sanitized = sanitized.replace(temp_root, "$TMP")
    return sanitized


def write_publish_proof(target: Path, git_initialized: bool, verify_output: str, demo_output: str) -> None:
    files = sorted(path for path in target.rglob("*") if path.is_file() and ".git" not in path.parts)
    release = target / ".release" / "shipgrade-cn-v0.1.tar.gz"
    proof = {
        "repo": "shipgrade-cn",
        "file_count": len(files),
        "git_initialized": git_initialized,
        "verify_output": verify_output.strip().splitlines()[-6:],
        "demo_output": demo_output.strip().splitlines()[-8:],
        "top_level": sorted(path.name for path in target.iterdir() if path.name != ".git")[:40],
        "sha256": {path.relative_to(target).as_posix(): sha256(path) for path in files[:80]},
    }
    (target / "PUBLISH_PROOF.md").write_text(
        "# Publish Proof\n\n"
        "This staged repository was generated by `scripts/create-public-stage.py`.\n\n"
        f"- file_count: `{proof['file_count']}`\n"
        f"- git_initialized: `{str(git_initialized).lower()}`\n"
        f"- verify_tail: `{'; '.join(proof['verify_output'])}`\n"
        f"- demo_tail: `{'; '.join(proof['demo_output'])}`\n"
        "- forbidden metadata scan: `passed`\n\n"
        "The stage intentionally excludes `.git`, `.release`, `.DS_Store`, `._*`, `__pycache__`, `.pyc`, and `.pyo` from the source copy.\n",
        encoding="utf-8",
    )
    (target / "publish-proof.json").write_text(json.dumps(proof, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a clean public GitHub staging copy of ShipGrade CN.")
    parser.add_argument("target", help="Empty or replaceable target directory.")
    parser.add_argument("--init-git", action="store_true", help="Initialize a git repository in the staged copy.")
    args = parser.parse_args()

    target = Path(args.target).expanduser().resolve()
    if target == ROOT or ROOT in target.parents:
        raise SystemExit("target must be outside the source repository")
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(ROOT, target, ignore=ignore)
    assert_clean(target)

    verify = run([sys.executable, "tools/shipgrade_verify.py"], cwd=target)
    if verify.returncode != 0:
        raise SystemExit(verify.stdout + verify.stderr)
    demo = run([sys.executable, "tools/shipgrade_demo.py", "--clean"], cwd=target)
    if demo.returncode != 0 or "shipgrade-demo-ok" not in demo.stdout:
        raise SystemExit(demo.stdout + demo.stderr)
    demo_output = sanitize_demo_output(demo.stdout)

    git_initialized = False
    if args.init_git:
        init = run(["git", "init", "-b", "main"], cwd=target)
        if init.returncode != 0:
            init = run(["git", "init"], cwd=target)
        if init.returncode == 0:
            git_initialized = True
        else:
            raise SystemExit(init.stdout + init.stderr)

    write_publish_proof(target, git_initialized, verify.stdout, demo_output)
    if git_initialized:
        add = run(["git", "add", "."], cwd=target)
        if add.returncode != 0:
            raise SystemExit(add.stdout + add.stderr)
    print(f"public-stage-ok path={target} git_initialized={str(git_initialized).lower()}")


if __name__ == "__main__":
    main()
